version: '3'
services:
  mysql:
    image: mysql:5.7
    volumes: 
      - ~/database/acm2019dev:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: admin1234
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin1234
      MYSQL_DATABASE: acm_development
    ports: 
      - 3306:3306
    expose: 
      - 3306
